name = "asr"
compatibility_date = "2025-05-17"
compatibility_flags = ["nodejs_compat"]

[build]
  command = "pnpm install && pnpm run build"

[observability.logs]
enabled = true

[assets]
directory = "./.next"
